[package]
name = "duckmate-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
clippy = "0.0.302"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
