[package]
name = "deep-duck"
version = "0.2.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
